import React from 'react';
import { FileText, ArrowLeft, CheckCircle2, Scale, AlertCircle } from 'lucide-react';
import { NavigationTab } from '../types';

interface TermsPageProps {
  onNavigate: (tab: NavigationTab) => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-[#f0f4f9] text-slate-900 font-sans p-4 lg:p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Navigation & Header */}
        <div className="flex items-center justify-between">
          <button
            type="button"
            onClick={() => onNavigate('dashboard')}
            className="flex items-center gap-2 px-3.5 py-2 rounded-lg bg-white border border-slate-200 text-slate-700 hover:text-slate-900 hover:bg-slate-50 text-[13px] font-semibold transition-all shadow-xs cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4 text-teal-700" />
            <span>Back to Dashboard</span>
          </button>
          <span className="font-mono text-[11px] font-semibold text-slate-500 bg-white px-3 py-1 rounded-full border border-slate-200">
            Version 1.2 • March 2026
          </span>
        </div>

        {/* Hero Card */}
        <div className="saas-card p-6 lg:p-8 space-y-3 bg-white border border-slate-200 rounded-2xl shadow-xs">
          <div className="flex items-center gap-2.5 text-teal-700 font-mono text-[12px] uppercase font-bold tracking-wider">
            <Scale className="w-5 h-5 text-teal-600" />
            <span>Terms of Service and Operational Guidelines</span>
          </div>
          <h1 className="text-2xl lg:text-3xl font-extrabold text-slate-900 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm text-slate-600 leading-relaxed max-w-3xl">
            Welcome to NagrikLens AI. By utilizing our civic intelligence platform, you agree to adhere to the following standard usage principles and open data protocols.
          </p>
        </div>

        {/* Terms Sections */}
        <div className="space-y-4">
          <div className="saas-card p-6 bg-white border border-slate-200 rounded-xl space-y-2.5 shadow-xs">
            <div className="flex items-center gap-2 text-slate-900 font-bold text-base">
              <CheckCircle2 className="w-4 h-4 text-teal-600" />
              <h2>1. Permitted Use and Citizen Reporting</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              NagrikLens AI provides a public interface for submitting genuine civic observations, local infrastructure complaints, and service queries. Users agree not to submit malicious payloads, fabricated emergency claims, or abusive material.
            </p>
          </div>

          <div className="saas-card p-6 bg-white border border-slate-200 rounded-xl space-y-2.5 shadow-xs">
            <div className="flex items-center gap-2 text-slate-900 font-bold text-base">
              <FileText className="w-4 h-4 text-teal-600" />
              <h2>2. Analytical Insights and Decision Support</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              Priority scores, demand clustering, and vector grounding metrics generated by NagrikLens AI serve as analytical decision support tools. Municipal authorities and civic stakeholders retain independent discretion for administrative actions and budget allocations.
            </p>
          </div>

          <div className="saas-card p-6 bg-white border border-slate-200 rounded-xl space-y-2.5 shadow-xs">
            <div className="flex items-center gap-2 text-slate-900 font-bold text-base">
              <AlertCircle className="w-4 h-4 text-teal-600" />
              <h2>3. Open Data Attribution</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">
              Public datasets ingested into the platform remain governed by the respective Open Government Data (OGD) licenses. NagrikLens AI maintains full traceability and source attribution for all corroborating records.
            </p>
          </div>
        </div>

        {/* Footer info */}
        <div className="text-center text-xs text-slate-500 py-4">
          NagrikLens AI • Transparent Civic Intelligence System
        </div>
      </div>
    </div>
  );
};
